baseURL = 'https://gregueria.icu/'
languageCode = 'zh-cn'
title = 'å†æœƒï¼Œè¬è¬æ‰€æœ‰çš„é­š'
theme = 'nostyleplease'
defaultContentLanguage = "zh"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true


[params.theme_config]
appearance = "dark"  # æˆ– "light"ï¼Œ"dark"

[params]
warning = """
  æœ¬ç«™å¯èƒ½åŒ…å«ä»¥ä¸‹å†…å®¹ï¼š
  <ul>
    <li>ğŸ’œ LGBTQIA+</li>
    <li>ğŸ–¤ Dark Thoughts</li>
    <li>ğŸ¤ NSFW Content</li>
  </ul>
  """
avatarurl = "/cat/tuxicon2.gif"
favicon = "images/favicon.png"



[[params.desktopicon]]
title = "Profile"
avatar = "/cat/cat69.gif"
profile_picture = "/cat/tuxicon2.gif"
profile_name = "é±¼é±¼ | She/her | Ace & Aro"
profile_descrpition = "ğŸ¤ æ‚¨çš„å¥¶ç‰›çŒ«å›¾ç‰‡è½¬å‘ä½¿è€…<br>ğŸ’œ ç‹‚çˆ±çŒ«ç‹—å¡‘åŒäººå¥³ä¸€æš<br>ğŸ–¤ æ›¾æˆåŠŸå®‰åˆ©125ä½è·¯è¿‡ç½‘å‹è§‚çœ‹ç”µå½±ã€Šæ— é—´é“2ã€‹"
window_id = "profile"  # å¯¹åº”çš„çª—å£ ID
social = [
    { name = "Archive of Our Own", url = "https://archiveofourown.org/users/timuk", avatar = "/icons/paper5.gif" },
    { name = "Fanfic Blog", url = "https://written.gregueria.icu/", avatar = "/icons/light4.gif" },
]
site_info_title = "More... â›³"
site_info_description = "èªªè¬Šè€…å¿ƒä¸­æ•µå°çš„ï¼Œä¸¦ä¸æ˜¯èª å¯¦çš„äººã€‚èªªè¬Šè€…æƒ³éŸé™¤çš„ï¼Œä¸æ˜¯åˆ¥äººï¼Œæ­£æ˜¯å°èªªå®¶ã€‚<br><p style=\"text-align: right;\">ã€Šæ°¸åˆ¥æ›¸ï¼šåœ¨æˆ‘ä¸åœ¨çš„æ™‚ä»£ã€‹</p>"

[[params.desktopicon]]
title = "Blog"
avatar = "/icons/bath4.gif"
window_id = "blog"

[[params.desktopicon]]
title = "Friends"
avatar = "/icons/cat75.gif"
window_id = "friends"

[[params.desktopicon]]
title = "Guest Book"
avatar = "/icons/light7.gif"
window_id = "guest_book"

[[params.desktopicon]]
title = "Cafe"
avatar = "/icons/bread7.gif"
window_id = "cafe"

[[params.desktopicon]]
title = "Changelog"
avatar = "/icons/bounce.gif"
window_id = "changelog"

